### ISSUE TITLE
Uninstall does not restore the original state

### ISSUE THREAD

**Issue by sebelk** [0x0I/ansible-role-journald#22]
Nice role, only I'd want to say that uninstall stage does not return to  to its configured state prior to application of this role.
I mean that I had to run manually something as follows:

`cp -p journald.conf.2336.2021-09-18@11\:09\:50~ journald.conf`

Greets

**Comment by O1ahmad** [comment]
Hey @sebelk 👋🏽 thanks ... and whoa, major apologies for the ridiculous delay in response - I've been pretty MIA working on these specific roles since I now support a more generic & flexible role. Anyway, I see your point and no worries  - I'll submit a change that cleans up all files on uninstall.
